#!/usr/bin/env bash

# Script bash para lanzar todos los algoritmos.
# Este script primero intenta hacer build del programa antes de lanzar las
# ejecuciones. El build se hace en modo --release para el maximo rendimiento.
# Los algoritmos greedy son los ultimos en lanzarse porque son los que nos dan problemas (en ocasiones
# pueden caer en ciclos infinitos)

# Construimos el binario
echo "Compilando el programa..."
cargo build --release
program="./target/release/PracticasMetaheuristicas"
echo ""

# Parametros del script
small_number_of_clusters=7
big_number_of_clusters=16
seeds=(
    123456789
    234567891
    3456789
    456789123
    567891234
)

# Colocamos las busquedas que queremos realizar en el orden deseado
# En la tercera practica solo tenemos que ejecutar las nuevas busquedas y copkmeans y localsearch
# Como tenemos los resultados de estas dos ultimas busquedas, solo ejecutamos las busquedas propias
# de la ultima practica
search_types=(
    multistartlocalsearch
    iterative_local_search
    iterative_local_search_annealing
    simulated_annealing

    # gguniform
    # ggsegment
    # gsuniform
    # gssegment
    # memeall
    # memerandom
    # memeelitist
    # local_search

    # # Copkmeans robust antes que copkmeans porque copkmeans se puede quedar colgado
    # copkmeans_robust
    # copkmeans
)

# Por cada tipo de busqueda, lanzamos la busqueda sobre las distintas semillas en los distintos datasets
for search_type in "${search_types[@]}"
do
    echo "==> Lanzando las busquedas tipo ${local_search}"
    for seed in "${seeds[@]}"
    do
        echo "Lanzando zoo en sus dos variantes de restricciones"
        $program ./data/zoo_set.dat ./data/zoo_set_const_10.const $seed $small_number_of_clusters $search_type
        $program ./data/zoo_set.dat ./data/zoo_set_const_20.const $seed $small_number_of_clusters $search_type
        echo ""

        echo "Lanzando glass en sus dos variantes de restricciones"
        $program ./data/glass_set.dat ./data/glass_set_const_10.const $seed $small_number_of_clusters $search_type
        $program ./data/glass_set.dat ./data/glass_set_const_20.const $seed $small_number_of_clusters $search_type
        echo ""

        echo "Lanzando bupa en sus dos variantes de restricciones"
        $program ./data/bupa_set.dat ./data/bupa_set_const_10.const $seed $big_number_of_clusters $search_type
        $program ./data/bupa_set.dat ./data/bupa_set_const_20.const $seed $big_number_of_clusters $search_type
        echo ""

    done
done
