#!/usr/bin/env bash

# Script bash para lanzar todos los algoritmos.
# Este script primero intenta hacer build del programa antes de lanzar las
# ejecuciones. El build se hace en modo --release para el maximo rendimiento.
# Los algoritmos greedy son los ultimos en lanzarse porque son los que nos dan problemas (en ocasiones
# pueden caer en ciclos infinitos)

# Construimos el binario
echo "Compilando el programa..."
cargo build --release
program="./target/release/PracticasMetaheuristicas"
echo ""

# Parametros del script
small_number_of_clusters=7
big_number_of_clusters=16
seeds=(
    123456789
    234567891
    3456789
    456789123
    567891234
)

# Lanzamos las busquedas locales
echo "==> Lanzando las busquedas locales"
for seed in "${seeds[@]}"
do
    echo "Lanzando zoo en sus dos variantes de restricciones"
    $program ./data/zoo_set.dat ./data/zoo_set_const_10.const $seed $small_number_of_clusters local_search
    $program ./data/zoo_set.dat ./data/zoo_set_const_20.const $seed $small_number_of_clusters local_search
    echo ""

    echo "Lanzando glass en sus dos variantes de restricciones"
    $program ./data/glass_set.dat ./data/glass_set_const_10.const $seed $small_number_of_clusters local_search
    $program ./data/glass_set.dat ./data/glass_set_const_20.const $seed $small_number_of_clusters local_search
    echo ""

    echo "Lanzando bupa en sus dos variantes de restricciones"
    $program ./data/bupa_set.dat ./data/bupa_set_const_10.const $seed $big_number_of_clusters local_search
    $program ./data/bupa_set.dat ./data/bupa_set_const_20.const $seed $big_number_of_clusters local_search
    echo ""

done

# Lanzamos los algoritmos greedy
echo "==> Lanzando los algoritmos greedy"
for seed in "${seeds[@]}"
do
    echo "Lanzando zoo en sus dos variantes de restricciones"
    $program ./data/zoo_set.dat ./data/zoo_set_const_10.const $seed $small_number_of_clusters copkmeans_robust
    $program ./data/zoo_set.dat ./data/zoo_set_const_20.const $seed $small_number_of_clusters copkmeans_robust
    echo ""

    echo "Lanzando glass en sus dos variantes de restricciones"
    $program ./data/glass_set.dat ./data/glass_set_const_10.const $seed $small_number_of_clusters copkmeans_robust
    $program ./data/glass_set.dat ./data/glass_set_const_20.const $seed $small_number_of_clusters copkmeans_robust
    echo ""

    echo "Lanzando bupa en sus dos variantes de restricciones"
    $program ./data/bupa_set.dat ./data/bupa_set_const_10.const $seed $big_number_of_clusters copkmeans_robust
    $program ./data/bupa_set.dat ./data/bupa_set_const_20.const $seed $big_number_of_clusters copkmeans_robust
    echo ""

done
